version: '3'
services:
  my-sql-server:
    container_name: my-sql-server
    image: drsimplegraffiti/java-api:mysql
    ports:
      - "3307:3307"

  java-crud-app:
    container_name: java_api
    image: java-api:latest
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://my-sql-server:3307/dream_shops_db
      - DATABASE_USERNAME=dbuser
      - DATABASE_PASSWORD=rootpass
    depends_on:
      - my-sql-server
