## Use the official MySQL Docker image
#FROM mysql:latest
#
## Set the MySQL root password (replace with your desired password)
#ENV MYSQL_ROOT_PASSWORD=Bassguitar1
#
## Set a non-root user and password (replace with your desired username and password)
#ENV MYSQL_USER=dbuser
#ENV MYSQL_PASSWORD=rootpass
#
## (Optional) Create a new database (replace with your desired database name)
#ENV MYSQL_DATABASE=dream_shops_db
#
## Expose the MySQL port
#EXPOSE 3307